name: ss2lf

on: 
  workflow_dispatch:
  
env:
  LINODE_CLI_TOKEN: ${{secrets.LINODE_CLI_TOKEN}}
  AKAMAI_CREDENTIALS: ${{secrets.AKAMAI_CREDENTIALS}}
  MAP_ID: ${{secrets.MAP_ID}}
  FIREWALL_ID: ${{secrets.FIREWALL_ID}}

jobs:
  ss2lf:
    runs-on: ubuntu-22.04
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Linode CLI
      run: pip3 install linode-cli --upgrade

    - name: Setup Akamai CLI
      run: |
        echo "$AKAMAI_CREDENTIALS" > ~/.edgerc
        chmod +x akamai
        ./akamai install firewall

    - name: Get SiteShield ip list
      run: |
        IP_LIST=`./akamai site-shield --section default list-cidrs --map-id $MAP_ID --json | jq -r '.proposedCidrs | @csv'`
    
    - name: Create allow ip list
      run: |
        ALLOW_IP_LIST=`printf '[{"protocol": "TCP", "ports": "443", "addresses": {"ipv4": [%s]}, "action": "ACCEPT"}]' $IP_LIST`

    - name: Update linode firewall
      run: |
        linode-cli firewalls rules-update $FIREWALL_ID --inbound $ALLOW_IP_LIST
