name: ss2lf

on: 
  workflow_dispatch:

jobs:
  ss2lf:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Setup Linode cli
      uses: brendon1555/setup-linode-cli@master
      with:
        LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
      - run: linode-cli --help
