name: ss2lf

on: 
  workflow_dispatch:
  
env:
  LINODE_CLI_TOKEN: ${{secrets.LINODE_CLI_TOKEN}}
  AKAMAI_CREDENTIALS: ${{secrets.AKAMAI_CREDENTIALS}}
  MAP_ID: ${{secrets.MAP_ID}}
  FIREWALL_ID: ${{secrets.FIREWALL_ID}}

jobs:
  ss2lf:
    runs-on: ubuntu-22.04
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Linode CLI
      run: pip3 install linode-cli --upgrade

    - name: Setup Akamai CLI
      run: |
        echo "$AKAMAI_CREDENTIALS" > ~/.edgerc
        chmod +x akamai
        ./akamai install firewall

    - name: Diff SS LF ip list
      run: |
        linode-cli firewalls rules-list $FIREWALL_ID --json | jq '.[].inbound[].addresses.ipv4' > lf.json
        ./akamai site-shield --section default list-cidrs --map-id $MAP_ID --json | jq -r '.proposedCidrs' > ss.json
        diff lf.json ss.json

    - name: Get SiteShield ip list
      run: |
        SS_IP_LIST=`./akamai site-shield --section default list-cidrs --map-id $MAP_ID --json | jq -r '.proposedCidrs | @csv'`
        echo "SS_IP_LIST=$SS_IP_LIST" >> $GITHUB_ENV

    - name: Create allow ip list
      run: |
        LF_IP_LIST=`printf '[{"protocol": "TCP", "ports": "443", "addresses": {"ipv4": [%s]}, "action": "ACCEPT"}]' $SS_IP_LIST`
        echo "LF_IP_LIST='$LF_IP_LIST'" >> $GITHUB_ENV

    - name: Update linode firewall
      run: |
        linode-cli firewalls rules-update $FIREWALL_ID --inbound ${{ env.LF_IP_LIST }}
